### ISSUE TITLE
[SUGGESTION] Add OptiFabric + OptiFine

### ISSUE THREAD

**Issue by gabrielvicenteYT** [renceron55th/Renceron-Vanilla-Legacy-Fabric#3]
OptiFabric legacy does exist, as it is shown here: https://github.com/RedLime/OptiFabric-Pre1.14
With OptiFabric, using OptiFine on the modpack will work just fine (though you still have to add BOTH). This will increase the FPS by a substantial amount, which is a good thing.

**Comment by renceron55th** [comment]
Good.I'll see how it works and add
